### ISSUE TITLE
Python 2 compatibility 

### ISSUE THREAD

**Issue by jakesherman** [dynobo/lmdiag#2]
@dynobo I want to start off by saying that I love this package. Inferential statistics is super easy in R thanks to things like `plot.lm`, so `lmdiag` really helps bridge the gap between Python and R! I was hunting down an easy way to do something similar to `plot.lm` in Python without having to manually build a bunch of the plots, so I was very happy to find this package. 

So I found one case in `info.py` where you used some Python 3-specific string formatting that causes this package to not work for Python 2. If you're only planning on having this be a Python 3 package, I completely respect that, though it would be nice if that were the case to add a note of that in the README. If you are interested in making this package work for Python 2, [here is a super quick fix I made in a fork of this package](https://github.com/jakesherman/lmdiag/commit/5dde773e633f2a92608b8650b0da0dd7b4d1e8b4) that fixes the issue for Python 2 (note: I haven't done extensive testing based on this fix, I just know it lets the package be imported without raising an error).

**Comment by dynobo** [comment]
@jakesherman Thanks for your Feedback! Highly appreciated! :) To be honest, I didn't even think about version compability yet.  I'll take a look at your fork and try incorporate the necessary changes in the next days.

**Comment by dynobo** [comment]
Note to myself: Nice site to check for other possible compat issues and how avoid them:

http://python-future.org/compatible_idioms.html

**Comment by dynobo** [comment]
Should be fixed with 077ef89 .

**Comment by dynobo** [comment]
Published Python 2 compatible version to PyPi. Please leave a note, if you have any issues.
